package com.jypLord.domain.trade;

public enum TradeStatus {

    ACTIVE,
    LOSSCUT_TRIGGERED,
    LOSSCUT_ORDER_SUBMITTED,
    EXECUTED_LOSSCUT,
    REBUY_WATCHING,
    REBUY_ORDER_SUBMITTED,
    EXECUTED_BUY,
    ORDER_FAILED,
    CANCELLED,
    EXPIRED
}
